### ISSUE TITLE
Use of LINQ - Performance Implications

### ISSUE THREAD

**Issue by kenofori** [taylorjg/pentominoes-cs#1]
Hi there,

First of all, thank you for providing a pure/console C# implementation of your amazing algorithm as this will allow to use it in Unity for mobile platforms.

Now, Sorry for asking a dumb question but as im targetting mobile devices where a rect could be as big as 100x100 = 10k cells. Isn't excessive use of LINQ going to be a performance problem? 

If thats the case i can make the changes myself but it'd be great i could use your amazing library with keeping it as official as possible and without making custom changes.

Thanks

**Comment by taylorjg** [comment]
I use a lot of LINQ in this repo to build the matrix. However, the bulk of the execution time will be spent inside the library solving the matrix rather than outside the library building the matrix. Internally, the library builds its own representation of the matrix. It creates an internal node for each `1` in the matrix. The `0`s in the matrix are ignored. In most cases, the matrix is very sparse consisting mainly of `0`s.
For example, in the case of this repo, each row in the matrix has 72 columns of which 6 are `1`s and 66 are `0`s. As the algorithm progresses inside the library, nodes are linked and unlinked (this is the 'dancing links' idea). So there isn't really any LINQ going on inside the library itself.

**Comment by taylorjg** [comment]
> First of all, thank you for providing a pure/console C# implementation of your amazing algorithm as this will allow to use it in Unity for mobile platforms.

Also, I'd just like to point out that it is not _my_ algorithm. It is Donald Knuth's algorithm:

https://en.wikipedia.org/wiki/Dancing_Links

**Comment by kenofori** [comment]
Thanks for explanation, looks like it shouldnt cause any issue when i try to run it on mobile.

sorry i meant your implementation of that algorithm, its a very rare C# implementation which is up to date.
